<?php
return [
    'entrepreneurship' => [
        'organization' => [
            '1' => 'Universidad',
            '2' => 'Redes sociales',
            '3' => 'Google',
            '4' => 'Medios de comunicación (Periódicos, Radio, TV, Artículos...)',
            '5' => 'Evento, foro o conferencia',
            '6' => 'Un amigo o conocido',
            '8' => 'Mprende',
        ],
    ],
    'talent' => [
        'organization' => [
            '1' => 'Universidad',
            '2' => 'Redes sociales',
            '3' => 'Google',
            '4' => 'Medios de comunicación (Periódicos, Radio, TV, Artículos...)',
            '5' => 'Evento, foro o conferencia',
            '6' => 'Un amigo o conocido',
        ],

    ],
    'voluntary' => [
        'organization' => [
            '1' => 'Universidad',
            '2' => 'Redes sociales',
            '3' => 'Google',
            '4' => 'Medios de comunicación (Periódicos, Radio, TV, Artículos...)',
            '5' => 'Youth Speak',
            '6' => 'Un amigo o conocido',
            '7' => 'Redes sociales de un amigo',
        ],

    ],
    'lists' => [
        'semester' => [
            1 => 1,
            2 => 2,
            3 => 3,
            4 => 4,
            5 => 5,
            6 => 6,
            7 => 7,
            8 => 8,
            9 => 9,
            10 => 10,
            11 => 'Graduado'
        ],
        'career' => [
            '1' => 'Actividad física y del Deporte',
            '2' => 'Administración de Recursos Humanos',
            '3' => 'Administración de empresas',
            '4' => 'Agronomía',
            '5' => 'Antropología',
            '6' => 'Arqueología',
            '7' => 'Arquitectura',
            '8' => 'Arte',
            '9' => 'Astronomía',
            '10' => 'Bibliotecología',
            '11' => 'Biología',
            '12' => 'Biología Química',
            '13' => 'Ciencia Política y Gobierno',
            '14' => 'Ciencia y Tecnología de los Alimentos',
            '15' => 'Ciencias Ambientales',
            '16' => 'Comercio Internacional',
            '17' => 'Comunicación Social',
            '18' => 'Contaduría Pública y Auditoría',
            '19' => 'Derecho',
            '20' => 'Diseño Gráfico',
            '21' => 'Diseño Industrial',
            '22' => 'Diseño de Interiores',
            '23' => 'Diseño de Modas',
            '24' => 'Economía',
            '25' => 'Enfermería',
            '26' => 'Estadística',
            '27' => 'Farmacia',
            '28' => 'Filología',
            '29' => 'Filosofía',
            '30' => 'Finanzas',
            '31' => 'Física',
            '32' => 'Geografía',
            '33' => 'Geología',
            '34' => 'Historia',
            '35' => 'Historia del Arte',
            '36' => 'Ingeniería Administrativa',
            '37' => 'Ingeniería Catastral y Geodesia',
            '38' => 'Ingeniería Civil',
            '39' => 'Ingeniería Electrónica',
            '40' => 'Ingeniería Eléctrica',
            '41' => 'Ingeniería Industrial',
            '42' => 'Ingeniería Mecánica',
            '43' => 'Ingeniería Multimedia',
            '44' => 'Ingeniería de Desarrollo de Producto',
            '45' => 'Ingeniería de Procesos',
            '46' => 'Ingeniería de Producción',
            '47' => 'Ingeniería en Agrimensura',
            '48' => 'Ingeniería en Petróleos',
            '49' => 'Ingeniería en Sistemas',
            '50' => 'Ingeniería en Telecomunicaciones',
            '51' => 'Ingeniería mecatrónica',
            '52' => 'Licenciatura en Español y Literatura',
            '53' => 'Licenciatura en Lenguas Extranjeras/Modernas',
            '54' => 'Liderazgo Organizacional',
            '55' => 'Lingüística',
            '56' => 'Literatura',
            '57' => 'Matemática',
            '58' => 'Medicina',
            '59' => 'Mercadotecnia',
            '60' => 'Música',
            '61' => 'Nutrición y Dietética',
            '62' => 'Odontología',
            '63' => 'Pedagogía',
            '64' => 'Periodismo',
            '65' => 'Psicología',
            '66' => 'Psicopedagogía',
            '67' => 'Publicidad y Relaciones Públicas',
            '68' => 'Química',
            '69' => 'Relaciones Internacionales',
            '70' => 'Sociología',
            '71' => 'Tecnología en análisis y desarrollo de sistemas de Información',
            '72' => 'Tecnología en negocios internacionales',
            '73' => 'Teología',
            '74' => 'Trabajo Social',
            '75' => 'Traducción e Interpretación',
            '76' => 'Turismo',
            '77' => 'Veterinaria',
            '78' => 'Zootecnia',
        ],
        'english_level' => [
            '1' => 'Básico',
            '2' => 'Intermedio',
            '3' => 'Avanzado',
        ],
        'travel_date' => [
            '1' => 'De hoy a 6 meses',
            '2' => 'De 6 meses un año',
            '3' => 'Sin fecha fija pero quiero conocer más',
        ],
        'preference_contact' => [
            '1' => 'Correo Electrónico',
            '2' => 'Llamada',
            '3' => 'Whatsapp',
        ],
        'experience' => [
            '1' => 'Menos de 3 meses de experiencia',
            '2' => '6 meses de experiencia',
            '3' => '1 año de experiencia',
            '4' => 'Más de 1 año de experiencia',
        ],
        'activities' => [
            ["id" => 742, "name" => "Training"],
            ["id" => 715, "name" => "Accounting / Auditing"],
            ["id" => 716, "name" => "Advertising"],
            ["id" => 717, "name" => "Analyst"],
            ["id" => 718, "name" => "Art / Creative"],
            ["id" => 719, "name" => "Business Development"],
            ["id" => 720, "name" => "Consulting"],
            ["id" => 721, "name" => "Customer Service"],
            ["id" => 722, "name" => "Design"],
            ["id" => 723, "name" => "Education"],
            ["id" => 724, "name" => "Engineering"],
            ["id" => 725, "name" => "Finance"],
            ["id" => 726, "name" => "Human Resources"],
            ["id" => 727, "name" => "Information Technology"],
            ["id" => 728, "name" => "Legal"],
            ["id" => 729, "name" => "Management"],
            ["id" => 730, "name" => "Marketing"],
            ["id" => 731, "name" => "Other"],
            ["id" => 732, "name" => "Public Relations"],
            ["id" => 733, "name" => "Purchasing"],
            ["id" => 734, "name" => "Product Management"],
            ["id" => 735, "name" => "Project Management"],
            ["id" => 736, "name" => "Production"],
            ["id" => 737, "name" => "Quality Assurance"],
            ["id" => 738, "name" => "Research"],
            ["id" => 739, "name" => "Sales"],
            ["id" => 740, "name" => "Strategy / Planning"],
            ["id" => 741, "name" => "Supply Chain"],
            ["id" => 743, "name" => "Writing / Editing"]
        ]
    ]

];